// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire@latest

package server

import (
	"git.myscrm.cn/ganqx01/ai-script/backend/internal/conf"
	"git.myscrm.cn/ganqx01/ai-script/backend/internal/handler"
	"git.myscrm.cn/ganqx01/ai-script/backend/internal/repo"
	"git.myscrm.cn/ganqx01/ai-script/backend/internal/service"
	"go.uber.org/zap"
)

// InitializeApp is the Wire injector for assembling the HTTP server application.
func InitializeApp(cfg *conf.Config, log *zap.Logger) (*App, error) {
	db, err := newDB(cfg, log)
	if err != nil {
		return nil, err
	}

	rdb := newRedis(cfg)

	modelPath := ProvideCasbinModelPath()
	enforcer, err := ProvideCasbin(db, modelPath)
	if err != nil {
		return nil, err
	}

	jwtMgr := ProvideJWTManager(cfg)

	repos := repo.NewRepositories(db, rdb)

	cipher, err := ProvideCipher(cfg)
	if err != nil {
		return nil, err
	}

	taskClient := ProvideTaskClient(cfg)
	registry := ProvideRegistry()

	store, err := ProvideStorage(cfg)
	if err != nil {
		return nil, err
	}

	hub := ProvideHub(cfg, log, rdb)

	services := service.NewServices(repos, jwtMgr, enforcer, cipher, registry, taskClient, hub, store, log)

	handlers := handler.NewHandlers(services, hub, log, rdb)

	app, err := NewApp(cfg, log, db, rdb, enforcer, jwtMgr, repos, services, hub, store, handlers)
	if err != nil {
		return nil, err
	}

	return app, nil
}
