swagger: "2.0"
info:
  description: AI 短剧视频生成平台 REST API 文档
  title: AI Script API
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
host: localhost:8080
basePath: /api/v1
paths: {}
