// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire@latest

package main

import (
	"github.com/godfreygan/ai-script/backend/internal/conf"
	"github.com/godfreygan/ai-script/backend/internal/repo"
	"github.com/godfreygan/ai-script/backend/internal/server"
	"github.com/godfreygan/ai-script/backend/internal/service"
	"go.uber.org/zap"
)

// InitializeWorker 是 worker 的 Wire 注入器。
func InitializeWorker(cfg *conf.Config, log *zap.Logger) (*WorkerDeps, error) {
	db, err := server.NewDB(cfg, log)
	if err != nil {
		return nil, err
	}

	rdb := server.NewRedis(cfg)

	modelPath := server.ProvideCasbinModelPath()
	enforcer, err := server.ProvideCasbin(db, modelPath)
	if err != nil {
		return nil, err
	}

	jwtMgr := server.ProvideJWTManager(cfg)

	repos := repo.NewRepositories(db, rdb)

	cipher, err := server.ProvideCipher(cfg)
	if err != nil {
		return nil, err
	}

	taskClient := server.ProvideTaskClient(cfg)
	registry := server.ProvideRegistry()

	store, err := server.ProvideStorage(cfg)
	if err != nil {
		return nil, err
	}

	hub := server.ProvideHub(cfg, log, rdb)

	services := service.NewServices(repos, jwtMgr, enforcer, cipher, registry, taskClient, hub, store, log)

	deps := &WorkerDeps{
		DB:       db,
		RDB:      rdb,
		Repos:    repos,
		Services: services,
		Registry: registry,
		Store:    store,
		Hub:      hub,
	}

	return deps, nil
}
